### ISSUE TITLE
StableBaselines Intergration

### ISSUE THREAD

**Issue by MentalGear** [aidudezzz/deepbots#42] opened 2020-09-12 10:55 UTC
Hey guys,
Pretty amazing work here. Actually found this only a day before having completed my own gym & [stableBaselines ](https://stable-baselines.readthedocs.io/en/master/) integration with Webots. But yours is a nice package format, so I actually prefer this I guess. Alright, here's  my question: Do you guys are already working on adding stableBaselines to deepbots, or should I give it a shot ?

**Comment by ManosMagnus** [comment] 2020-09-12 14:28
Hello @MentalGear,

Thanking for opening this issue. Indeed, integrating stableBaseline is one of our future plans. However, this isn't something that we are currently working on. It is more than welcome to give it a shot and we will be happy to help you. I feel that it will be an awesome enchantment.

It seems, with a quick look,  that the compatibility is broken because that the [SupervisorEnv](https://github.com/aidudezzz/deepbots/blob/master/deepbots/supervisor/controllers/supervisor_env.py) doesn't have some extra attributes OpenGym uses (ex. [action_space, observation_space](https://github.com/openai/gym/blob/8cf2685db25572e4fd6716565694d05f83000d60/gym/core.py#L37-L38)) which they are necessary to the stableBaselines (for example in [DDPG](https://github.com/hill-a/stable-baselines/blob/3d115a3f1f5a755dc92b803a1f5499c24158fb21/stable_baselines/ddpg/ddpg.py#L877)). I feel that this is a good staring point.

You can use the [deepworlds repository](https://github.com/aidudezzz/deepworlds) which has already some implemented examples to test your code and feel free to contacting us, open PRs, ask for help or request a code review. 

cheers

**Comment by ManosMagnus** [comment] 2021-02-17 10:25
Hello @MentalGear, stable baselines can be integrated using the [latest-dev](https://test.pypi.org/project/deepbots/) version of deepbots. We will happy to hear if that works for you.

Any feedback will be appreciated!

**Comment by ManosMagnus** [comment] 2021-02-17 10:27
@all-contributors please add @MentalGear  for ideas

**Comment by tsampazk** [comment] 2021-12-05 12:25
Issue is a duplicate of #85

**Closed by tsampazk** 2021-12-05 12:25 UTC
Labels: duplicate, enhancement, refactor
